name: Build Ionic Android

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Use Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '8.x'
#     - run: npm install -g ionic@3 
#     - run: npm install -g cordova@7
#     - run: npm install
#     - run: npm i @ionic/app-scripts@3.2.2
#     - name: Cordova
#       working-directory: ./
#       run: ionic cordova build android
      
#     - name: Build debug APK
#       working-directory: ./platforms/android      
#       run: bash ./gradlew assembleDebug --stacktrace
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8

    - name: Build
      run: ionic cordova build android
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
#         path: ./platforms/android
        path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
